version: "2"

services:
  test:
      build:
        context: .
        dockerfile: Dockerfile.test
      volumes:
        - ./test-results:/app/test-results
      command: ["npx", "vitest", "--reporter=json", "--outputFile=./test-results/test-output.json"]

       