apiVersion: v1
kind: Service
metadata:
  name: gewobackend
  labels:
    name: gewobackend
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    name: gewobackend
