name: 'Terraform'

on:
  workflow_dispatch:
    inputs:
      destroy:
        description: 'Set to 1 to destroy the terraform architecture'     
        required: false
        default: '0'

permissions:
  contents: read

jobs:
  be_build_tests:
    name: 'Backend Build Tests'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ./backend

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Go 1.22.x
      uses: actions/setup-go@v5
      with:
        go-version: 1.22.x
        cache-dependency-path: "backend/go.sum"
    
    - name: Build Swagger
      run: |
        go install github.com/swaggo/swag/cmd/swag@latest
        swag init -g handler.go 
    
    - name: Build Backend
      run: |
        make build-deployment

    - name: 'Uploading Artefact'
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: backend_artifact
        path: ./backend/bin
        retention-days: 1