name: Frontend CI

on:
  push:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend_ci.yml'
  pull_request:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend_ci.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend/vue-gewoscout
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v4
      - name: Run Tests
        run: docker-compose -f docker-compose.yaml run test
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            frontend/vue-gewoscout/test-results/*.xml
      - name: TearDown docker compose
        run: docker-compose down --remove-orphans
