name: Frontend CI

on:
  push:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend_ci.yml'
  pull_request:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend_ci.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend/vue-gewoscout
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v4
      
      - name: Run Tests
        run: docker-compose -f docker-compose.yaml run test
      
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            frontend/vue-gewoscout/test-results/*.xml
      
      - name: TearDown docker compose
        run: docker-compose down --remove-orphans
      
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.SWA_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          app_location: "/" # App source code path
          output_location: "dist" # Built app content directory - optional
          deployment_environment: Development