name: Build the homework
on: [push]

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: ./src

    steps:
    - uses: actions/checkout@v4

    - name: Buildah Action
      uses: redhat-actions/buildah-build@v2
      with:
        image: my-new-image
        tags: v1 ${{ github.sha }}
        containerfiles: |
          ./Dockerfile